export const iconsArray: string[] = [
    'alarm',
    'archive',
    'award',
    'bag',
    'bandaid',
    'bank',
    'basket',
    'basket2',
    'basket3',
    'bell',
    'bicycle',
    'binoculars',
    'book',
    'bookshelf',
    'boombox',
    'box',
    'boxes',
    'boxSeam',
    'bricks',
    'briefcase',
    'brightnessHigh',
    'brush',
    'bucket',
    'bug',
    'building',
    'calculator',
    'camera',
    'cameraReels',
    'cart2',
    'cashCoin',
    'clock',
    'cloud',
    'cloudDrizzle',
    'cloudMoon',
    'clouds',
    'cloudSnow',
    'coin',
    'compass',
    'controller',
    'cup',
    'cupStraw',
    'dice5',
    'disc',
    'display',
    'doorClosed',
    'doorOpen',
    'dpad',
    'droplet',
    'easel',
    'egg',
    'eggFried',
    'emojiHeartEyes',
    'emojiLaughing',
    'emojiSmile',
    'emojiSmileUpsideDown',
    'emojiSunglasses',
    'emojiWink',
    'envelope',
    'eyeglasses',
    'flag',
    'flower1',
    'flower2',
    'flower3',
    'gem',
    'gift',
    'globe',
    'globe2',
    'handbag',
    'handThumbsUp',
    'hdd',
    'heart',
    'hourglass',
    'hourglassSplit',
    'house',
    'houseDoor',
    'inbox',
    'inboxes',
    'key',
    'keyboard',
    'ladder',
    'lamp',
    'laptop',
    'lightbulb',
    'lightning',
    'lightningCharge',
    'lock',
    'magic',
    'mailbox',
    'map',
    'megaphone',
    'minecart',
    'minecartLoaded',
    'moon',
    'moonStars',
    'mortarboard',
    'mouse',
    'mouse2',
    'newspaper',
    'paintBucket',
    'palette',
    'palette2',
    'paperclip',
    'pen',
    'pencil',
    'phone',
    'piggyBank',
    'pinAngle',
    'plug',
    'printer',
    'projector',
    'puzzle',
    'router',
    'scissors',
    'sdCard',
    'search'
  ];

  function generateHashArray(count: number) {
    const hexArray: string[] = [];
  
    for (let i = 0; i < count; i++) {
  
      hexArray.push(hexColor());
    }
  
    return hexArray;
  }
  
  function hexColor() {
    const colorHex = `${Math.floor(Math.random()*16777215).toString(16)}`;

    return colorHex
  }
  
  export const hexArray: string[] = generateHashArray(100);
  
  